### ISSUE TITLE
PRACTICA 1

### ISSUE THREAD

**Issue by Brenda-hub2** [SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipo-irving#5]
[Practica 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipo-irving/files/10844541/Practica.1.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
